### ISSUE TITLE
Can't get this custom component to work

### ISSUE THREAD

**Issue by dextraa9791** [kadima-tech/experia-v10-device-tracker#4]
I followed the instructions but when i check my config it comes with the error "Integration experiaboxv10 not found when trying to verify its device_tracker platform.". Im running hassio.

![image](https://user-images.githubusercontent.com/47010783/56759277-e53a3d80-6798-11e9-874e-6f2c19203680.png)

**Comment by Denniz03** [comment]
i have the same problem

**Comment by erikvangils** [comment]
Probably you're using a recent version of Home Assistant (0.92 and up) in which the custom components structure has changed. I've implemented the changes that were necessary, and submitted a [pull request.](https://github.com/kadima-tech/experia-v10-device-tracker/pull/5) Meanwhile you might check if [my changes ](https://github.com/erikvangils/experia-v10-device-tracker) are working for you as well.

**Comment by Denniz03** [comment]
hoi Erik,ik zal in de loop van de week eens kijken, bedankt!Met vriendelijke groet,Danny Korthout
-------- Oorspronkelijk bericht --------Van: erikvangils <notifications@github.com> Datum: 05-05-19  15:44  (GMT+01:00) Aan: kadima-tech/experia-v10-device-tracker <experia-v10-device-tracker@noreply.github.com> Cc: Denniz03 <Danny.korthout@gmail.com>, Comment <comment@noreply.github.com> Onderwerp: Re: [kadima-tech/experia-v10-device-tracker] Can't get this custom component to work (#4) Probably you're using a recent version of Home Assistant (0.92 and up) in which the custom components structure has changed. I've implemented the changes that were necessary, and submitted a pull request. Meanwhile you might check if my changes  are working for you as well.

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/kadima-tech/experia-v10-device-tracker/issues/4#issuecomment-489427873",
"url": "https://github.com/kadima-tech/experia-v10-device-tracker/issues/4#issuecomment-489427873",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by sjaakiejj** [comment]
Thanks @erikvangils , I've just merged your pull request and created a [new release](https://github.com/kadima-tech/experia-v10-device-tracker/releases/tag/1.1.0). With that I will mark this issue resolved.
