### ISSUE TITLE
upgrade device tracker to use new known devices API

### ISSUE THREAD

**Issue by Requinard** [kadima-tech/experia-v10-device-tracker#8]
as per 0.94, known_devices.yaml is being phased out in favor of a new, UI-based config. An upgrade to this new API would be appreciated.

https://www.home-assistant.io/components/device_tracker/#known_devicesyaml

**Comment by Requinard** [comment]
see the following as a reference, as the experiabox v10a has a correct implementation.

https://github.com/FrankZZ/homeassistant-experiabox-v10a/blob/master/experiaboxv10a/device_tracker.py#L165

**Comment by sjaakiejj** [comment]
I've started work on this update. As part of it, I'll also be adding unit tests for the basic functionality of the scanner. I'll push out an update later this week.

**Comment by sjaakiejj** [comment]
The work-in-progress version can be found here:
https://github.com/kadima-tech/experia-v10-device-tracker/tree/known-devices-api-migration

Feel free to test if it works for you and please provide feedback if it doesn't.

**Comment by sjaakiejj** [comment]
I've got this running now, but I notice that due to my router not being updated to the latest firmware, the version of the code on Github right now does not support my home setup. I'll need to pull apart functionality so that both mechanisms can be supported, and perhaps a version check may be performed to select which mechanism to use. 

Other than that, this version of the code appears to work correctly. I'll close this issue and merge the code. Please get back to me if there are any more problems with this.
